version: '3.8'

services:
  backend:
    image: chrisc2c/my-backend:latest
    ports:
      - "2024:2024"
    env_file:
      - ./backend/.env.production
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    image: chrisc2c/my-frontend:latest
    ports:
      - "80:3000"
    env_file:
      - ./frontend/.env.production
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge